/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YYGcvLJILKo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"

export function Posts() {
  return (
    <div className="bg-gray-50 dark:bg-gray-900">
      <div className="px-4 py-6 md:px-6 md:py-12 lg:py-16">
        <div className="grid gap-6 lg:grid-cols-2 xl:gap-8">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tight">Taxing Laughter: The Joke Tax Chronicles</h2>
            <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
            <p>
              Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his throne.
              One day, his advisors came to him with a problem: the kingdom was running out of money.
            </p>
          </div>
          <div className="flex items-start">
            <Link className="ml-auto text-sm font-medium underline" href="#">
              Read
            </Link>
          </div>
        </div>
        <div className="grid gap-6 lg:grid-cols-2 xl:gap-8">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tight">The Mystery of the Missing Socks</h2>
            <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
            <p>
              Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his throne.
              One day, his advisors came to him with a problem: the kingdom was running out of money.
            </p>
          </div>
          <div className="flex items-start">
            <Link className="ml-auto text-sm font-medium underline" href="#">
              Read
            </Link>
          </div>
        </div>
        <div className="grid gap-6 lg:grid-cols-2 xl:gap-8">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tight">The Case of the Cackling Ghost</h2>
            <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
            <p>
              Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his throne.
              One day, his advisors came to him with a problem: the kingdom was running out of money.
            </p>
          </div>
          <div className="flex items-start">
            <Link className="ml-auto text-sm font-medium underline" href="#">
              Read
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
